export const items: { [key: string]: string[] } = {
  repair: ['Potpuni'],
  lock: ['Obični', 'Poboljšana', 'Napredni'],
  engine: ['default', 'STAGE 1', 'STAGE 2', 'STAGE 3', 'STAGE 4'],
  transmission: ['default', 'Ulični', 'Sportski', 'Trkaći'],
  brakes: ['default', 'Ulični', 'Sportski', 'Trkaći'],
  turbo: ['default', 'Turbo'],
  suspension: ['default', 'Niži', 'Ulični', 'Sportski', 'Trkaći'],
  armor: ['default', '20%', '40%', '60%', '80%', '100%'],
  engine_sound: [
    '6.0L V8',
    '3.0L I6',
    '5.2L V10',
    '2.6L I6',
    '1.3L Twin-Rotor',
    '5.8L Twin-Charged V8',
    '7.3L V12',
    '6.0L V12',
    '2.0L I4',
    '4.0L Flat-6',
    '5.2L V8',
  ],
  horn: [
    'default',
    'kamion',
    'policijski',
    'klaun',
    'Muzički 1',
    'Мuzički 2',
    'Muzički 3',
    'Muzički 4',
    'Muzički 5',
    'Tužna truba',
    'Klasični 1',
    'Klasični 2',
    'Klasični 3',
    'Klasični 4',
    'Klasični 5',
    'Klasični 6',
    'Кlasični 7',
    'Nota - C',
    'Nota - D',
    'Nota - E',
    'Nota - F',
    'Nota - G',
    'Nota - A',
    'Nota - H',
    'Nota - C (visoko)',
    'Jezz 1',
    'Jezz 2',
    'Jezz 3',
    'Jezz (ponavljanje)',
  ],
  tint: ['default', 'Pure black', 'Dark smoke', 'Light smoke', 'Limo', 'Green'],
  lights: [
    'default',
    'Bijeli',
    'Plavi',
    'Svijetlo plava',
    'Zelena',
    'Svijetlo zelena',
    'Svijetlo žuta',
    'Žuta',
    'Narančasta',
    'Crvena',
    'Ružičasta',
    'Ljubičasta',
    'Svijetlo ljubičasta',
  ],
  neon: ['default', 'Instalirati'],
  plate: [
    'default',
    'Žuto na crnom',
    'Žuto na plavom',
    'Plavo na bijelom #2',
    'Plavo na bijelom #3',
    'Crno na bijelom',
  ],
  paint: ['Glavna boja', 'Dodatna boja', 'Boja kotača', 'Dim od  guma'],
  rims: [],
  spoiler: [],
  sideskirt: [],
  exhaust: [],
  hood: [],
  roof: [],
  frame: [],
  grille: [],
  livery: [],
  front_bumper: [],
  rear_bumper: [],
};
